name: Shaka Page
description: something like my blog
footer-links:
    twitter: shaka0maru
theme: jekyll-theme-slate
sass:
    style: compressed

gems:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
